baseURL = "https://www.brtech.ie/"
languageCode = "pt-br"
theme = "hugo-bearblog"
title = "Tech para brasileiros na Ilha Esmeralda"
	

[[menu.main]]
	name = "RSS"
	url = "https://www.brtech.ie/index.xml"

[[menu.main]]
	name = "Direitos Trabalhistas"
	url = "/direitos/"
